# Rustfmt configuration for Egide
# https://rust-lang.github.io/rustfmt/

edition = "2021"

# Line width
max_width = 100
use_small_heuristics = "Default"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
wrap_comments = false
normalize_comments = false
normalize_doc_attributes = true

# Formatting
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Functions
fn_single_line = false
fn_params_layout = "Tall"

# Match
match_block_trailing_comma = true

# Structs
struct_lit_single_line = true
